apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./k8s-prod/auth-depl.yaml
- ./k8s/auth-mongo-depl.yaml
- ./k8s-prod/expiration-depl.yaml
- ./k8s/expiration-redis-depl.yaml
- ./k8s/nats-depl.yaml
- ./k8s-prod/position-depl.yaml
- ./k8s/position-mongo-depl.yaml
- ./k8s-prod/ingress-srv.yaml
namespace: geo
images:
- name: alexandersarson/geo-auth
  newName: alexandersarson/geo-auth
  newTag: 965b1023d24dfdffb1d49eb3bdc006d4b3315854
- name: alexandersarson/geo-expiration
  newName: alexandersarson/geo-expiration
  newTag: df5c166dbe0df411d8fa006f2f1b91061f9a386d
- name: alexandersarson/geo-position
  newName: alexandersarson/geo-position
  newTag: ea8482b628b1c07508d5f20ebab875664d642666
