apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./k8s/auth-depl.yaml
- ./k8s/auth-mongo-depl.yaml
- ./k8s/expiration-depl.yaml
- ./k8s/expiration-redis-depl.yaml
- ./k8s/nats-depl.yaml
- ./k8s/position-depl.yaml
- ./k8s/position-mongo-depl.yaml
- ./k8s-prod/ingress-srv.yaml
namespace: geo
images:
- name: alexandersarson/geo-auth
  newName: alexandersarson/geo-auth
  newTag: e3c9b0b8932c87ee8e04260a0b2debaa731d9a8d
- name: alexandersarson/geo-expiration
  newName: alexandersarson/geo-expiration
  newTag: 29058743532df83f9f989a8a8566d5147b490615
- name: alexandersarson/geo-position
  newName: alexandersarson/geo-position
  newTag: 45f3a66e818e316e1f8837be7b2c1751a316b30a
