apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./k8s/auth-depl.yaml
- ./k8s/auth-mongo-depl.yaml
- ./k8s/expiration-depl.yaml
- ./k8s/expiration-redis-depl.yaml
- ./k8s/nats-depl.yaml
- ./k8s/position-depl.yaml
- ./k8s/position-mongo-depl.yaml
- ./k8s-prod/ingress-srv.yaml
namespace: geo
images:
- name: alexandersarson/geo-auth
  newName: alexandersarson/geo-auth
  newTag: f044a70a6bc45ca701642246583b4ce1b267c290
- name: alexandersarson/geo-expiration
  newName: alexandersarson/geo-expiration
  newTag: 3f9465f0e1b99d6a7a340bb139384f5dfa09540b
- name: alexandersarson/geo-position
  newName: alexandersarson/geo-position
  newTag: 2c90ede87013b12218f9865598f0d87941c937d8
