apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./k8s/auth-depl.yaml
  - ./k8s/auth-mongo-depl.yaml
  - ./k8s/expiration-depl.yaml
  - ./k8s/expiration-redis-depl.yaml
  - ./k8s/nats-depl.yaml
  - ./k8s/position-depl.yaml
  - ./k8s/position-mongo-depl.yaml
namespace: geo
images:
  - name: alexandersarson/geo-auth
  - name: alexandersarson/geo-position
  - name: alexandersarson/geo-expiration
