apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./k8s-prod/auth-depl.yaml
- ./k8s/auth-mongo-depl.yaml
- ./k8s-prod/expiration-depl.yaml
- ./k8s/expiration-redis-depl.yaml
- ./k8s/nats-depl.yaml
- ./k8s-prod/position-depl.yaml
- ./k8s/position-mongo-depl.yaml
- ./k8s-prod/ingress-srv.yaml
namespace: geo
images:
- name: alexandersarson/geo-auth
  newName: alexandersarson/geo-auth
  newTag: 965b1023d24dfdffb1d49eb3bdc006d4b3315854
- name: alexandersarson/geo-expiration
  newName: alexandersarson/geo-expiration
  newTag: 3f9465f0e1b99d6a7a340bb139384f5dfa09540b
- name: alexandersarson/geo-position
  newName: alexandersarson/geo-position
  newTag: 32ab9e9a0b6e0d15a66b5bad686f1972c8756e96
