apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./k8s/auth-depl.yaml
- ./k8s/auth-mongo-depl.yaml
- ./k8s/expiration-depl.yaml
- ./k8s/expiration-redis-depl.yaml
- ./k8s/nats-depl.yaml
- ./k8s/position-depl.yaml
- ./k8s/position-mongo-depl.yaml
- ./k8s-prod/ingress-srv.yaml
namespace: geo
images:
- name: alexandersarson/geo-auth
  newName: alexandersarson/geo-auth
  newTag: f044a70a6bc45ca701642246583b4ce1b267c290
- name: alexandersarson/geo-expiration
  newName: alexandersarson/geo-expiration
  newTag: be3dcbbdb10a38f2c707cd8c86083501e570f68c
- name: alexandersarson/geo-position
  newName: alexandersarson/geo-position
  newTag: 1ed7cb423e34f88fe448268e1d43499ea0707a14
